ALTER SESSION SET CONTAINER = XEPDB1;

-- Create app user and grant privileges
CREATE USER app_user IDENTIFIED BY "app_password";
GRANT CONNECT, RESOURCE TO app_user;
GRANT UNLIMITED TABLESPACE TO app_user;
GRANT CREATE SESSION TO app_user;
GRANT CREATE TABLE TO app_user;
GRANT CREATE SEQUENCE TO app_user;
GRANT CREATE TRIGGER TO app_user;